build: add `-Wno-typedef-redefinition`
Code in `arch/x86/include/asm/rqspinlock.h` performs a typedef
redefinition which is a C11+ feature, causing noisy warnings (and/or
build failures due to `-Werror`, if a debug build is performed) while
building ZFS because the latter is built with GNU C99:

-- 8< --
In file included from ./include/linux/security.h:35:
In file included from ./include/linux/bpf.h:33:
In file included from ./arch/x86/include/asm/rqspinlock.h:31:
./include/asm-generic/rqspinlock.h:35:26: error: redefinition of typedef 'rqspinlock_t' is a C11 feature [-Werror,-Wtypedef-redefinition]
35 | typedef struct qspinlock rqspinlock_t;
  |                          ^
./arch/x86/include/asm/rqspinlock.h:17:26: note: previous definition is here
17 | typedef struct qspinlock rqspinlock_t;
  |                          ^
1 error generated.
-- 8< --

Suppress this specific warning because we can't do much about it.